### ISSUE TITLE
file request

### ISSUE THREAD

**Issue by MSDP4DOM** [knu-lcbc/Transformer_RetroTRAE#7]
Amazing work, thanks for your contribution! I tried to interpret the work by replicating the codes, however, when I run the `retrotrae\src\train.py` I got an `FileNotFoundError: [Errno 2] No such file or directory: 'data/src/bi_train.txt'`, I followed the clue find that `trian.txt` was defined in`parameters.py`, But I can't find the files in this repository. Maybe I missed something, could you please help fix it? Mant thanks!

**Comment by ashyrmamatov01** [comment]
Thank you for your interest in our work. 

In order to train a model from scratch, please follow the following steps:
1. **Extract** raw data after clonning the Github repo:
```
tar -xf data/raw_data.tar.bz2 -C data/
```
2.  Apply **tokenization scheme** and **split** the data:

   ```
   python src/tokenizer_with_split.py --model_type='bi'
   ```
`--model_type` option can be `uni` or `bi`
   
  3. Start **training**. Use `--help` option to check the training arguments.
   ```
   python src/train.py --model_type='bi'
   ```

Please refer to the **Training** section in the [`README.md`](https://github.com/knu-lcbc/RetroTRAE/edit/main/README.md) file.

**Comment by MSDP4DOM** [comment]
Thank you so much for your kind response! it works!
